# Please check the parameters, and adjust them according to your circumstance
INPUTPATH: "output/countFile"
OUTPUTPATH: "output/dea"
METAFILE: "configs/metadata.tsv"

PAIR: TRUE  # Is this a pair test or not? (TRUE or FALSE)

## the comparison(s) you want to do. If multiple comparisons, specify each pair (CONTROL & TREAT) in order respectively
CONTROL: ["DMSO", "DMSO", "DMSO", "DMSO", "DMSO", "DMSO"]
TREAT: ["BaP_low", "BaP_high", "EE2_low", "EE2_high", "Mix_low", "Mix_high"]
## length of 'CONTROL' should agree with that of 'TREAT'
## what you fill in there should agree with the "group" column in metadata.tsv

FILTER:
  yesOrNo: TRUE  # Filter out low expressed genes or not? (TRUE or FALSE)
  cpm: 1  # if yes for filter, what's the threshold of cpm?
